### ISSUE TITLE
Info on adding support to other services (i.e. TIDAL)

### ISSUE THREAD

**Issue by etinin** [JakubSteplowski/SpotifyLyricsNET#8]
So, Tidal doesn't really have any alternatives on Windows to show the lyrics of the song which is currently playing. Turns out if you just change the process name to TIDAL, this software works perfectly with that service as well. Maybe do something less lazy than I did and add a toggle option? Shouldn't be too hard.

Basically, just replace the 3 or 4 lines which refer to the "Spotify" process with "TIDAL". Users of this service will find this most interesting, since there is no Musixmatch or anything for this platform.

Also need to reverse the order of artist and song title. Everything else is looking fine.

https://github.com/etinin/SpotifyLyricsNET/blob/master/README.md

**Comment by JakubSteplowski** [comment]
Thanks for the tip!

I wonder if this could work also with other services (e.g Deezer, Apple Music). 🤔
Anyway, awesome discovery, thanks!

I think a separate program for that would be better, instead of a toggle in the app.
For a few reasons:
- It will be easier to find the right target.
- I plan to implement a few Spotify only features in the future.

In my spare time I will create a new repo of TIDAL Lyrics .NET with a slightly different UI, and I will try to update them both simultaneously in the future.

Let me know if you want to be in the credits (I think it's fair).

**Comment by etinin** [comment]
if you ever get to it, feel free to add some small credits but the main work is all yours ;)
i'll try to help if I get the time

**Comment by JakubSteplowski** [comment]
I created and released the first version of TIDAL Lyrics .NET (v1.6.0):
https://github.com/JakubSteplowski/TIDAL_LyricsNET

Thanks again for your help! :)

**Comment by JakubSteplowski** [comment]
Plot twist: 
Tidal Music AS (it should be ASS) sued me for "Intellectual Property Rights and Other Violations". 😊

I had to remove it, unfortunately.
