### ISSUE TITLE
Download size of source code

### ISSUE THREAD

**Issue by acosano** [JakubSteplowski/SpotifyLyricsNET#9]
Hi,

Trying to download the source code but I'm already on 400 MB download and it is not yet 1%. I'm not sure if I'm doing something wrong but  would appreciate if you could have a look at it and let me know.

Happy New Year from Sydney Australia.

**Comment by JakubSteplowski** [comment]
Hi,

Sorry for the inconvenience.
The source code packages weighs about 924 MB.
The reason is that it contains 4 projects (stable & alpha WPF & UWP), the UWP one also contains the compiled packages (my fault, I thought the bin folder isn't included in the generated .zip).

I updated the release (https://github.com/JakubSteplowski/SpotifyLyricsNET/releases/tag/v1.6.0)  by adding two new .zips without useless stuff in them:
- Spotify Lyrics .NET - v1.6.0 - WPF Source.zip (86 MB)
- Spotify Lyrics .NET - v1.6.0 - UWP Source.zip (232 MB)

Best regards and Happy New Year too!

**Comment by yazdipour** [comment]
You need to add gitignore (https://www.gitignore.io/api/visualstudio) and remove compiled files.

**Comment by JakubSteplowski** [comment]
> You need to add gitignore (https://www.gitignore.io/api/visualstudio) and remove compiled files.

You're right, my bad.
Thank you! :)
